[sprint/3/-web-api]:add new web api and localStoreg
sanfranboys/arcanoid pull request #47
Opened 2021-03-04 13:45 UTC by Domion-M

2021-03-13 15:05 UTC, Dihlofos requested changes

2021-03-13 15:05 UTC, Dihlofos commented on src/utils/browserNotification.ts
> +    storage('notification') || '{ "date":0 }'
"date" - это что? время, когда человек подписался? я подписался и у меня вот так, 6, и все, этих данных достаточно?
![image](https://user-images.githubusercontent.com/14941049/111034344-36538900-8426-11eb-9419-7383b49bc206.png)

2021-03-13 15:05 UTC, Dihlofos commented on src/utils/setLocalStorage.ts
> +const storage = (key: NotificationKey, value?: any) => {
давай назовем эту штуку "getFromLocalStorage" потому что сейчас из названия не очень понятно что она делает

2021-03-14 03:45 UTC, malig approved these changes

2021-03-14 03:45 UTC, malig commented on src/pages/LeaderboardPage/components/LeaderCard/LeaderCard.tsx
> +      className={`leader-card_place_${position}`}
Почему стало не по бэм? card place это не элемент карточки, а модификатор со значением, который всего лишь меняет цвет бордера, такие забивается через два одинарных подчерка.

2021-03-14 08:01 UTC, Domion-M commented on src/utils/browserNotification.ts
> +    storage('notification') || '{ "date":0 }'
Оповещение должно сработать один раз в день и если время больше 8 часов , если меньше то кидается таймаут

2021-03-14 08:01 UTC, Domion-M commented on src/utils/browserNotification.ts
> +    storage('notification') || '{ "date":0 }'
тут можно придумать как угодно я думаю сейчас это не столь актуально

2021-03-16 05:39 UTC, Dihlofos approved these changes

2021-03-18 04:55 UTC, eshturman requested changes

2021-03-18 04:55 UTC, eshturman commented on src/utils/browserNotification.ts
> +  notification.onshow = () => storage('notification', { date: dateNow })
onShow

2021-03-18 05:49 UTC, Domion-M commented on src/utils/browserNotification.ts
> +  notification.onshow = () => storage('notification', { date: dateNow })
тут зарезервированный метод

2021-03-20 13:25 UTC, merged