Backlog/19/ pausa
sanfranboys/arcanoid pull request #48
Opened 2021-03-09 05:02 UTC by Domion-M

2021-03-11 05:35 UTC, Dihlofos requested changes
Отметил пару мелочей чисто структурных, а также не хватает на стартовом экране текста "Нажмите пробел, чтобы начать игру" Я лично пытался нажимать на кнопку мышки сперва))

2021-03-11 05:35 UTC, Dihlofos commented on src/pages/GameProccessPage/sanfranoid/Lives.ts
> +  img: any
здесь нужен тип, HTMLImageElement[] вроде подходит

2021-03-11 05:35 UTC, Dihlofos commented on src/pages/GameProccessPage/sanfranoid/Lives.ts
> +    this.img = new Array(3).fill('').map(() => {
А давай добавим "3" в конструктор, чтобы можно было менять максимальное количество жизни в коде самой игры, а не в коде конкретного класса.
Причем, у тебя уже эта переменная есть в файле settings, ты видимо планировал так и сделать но руки не дошли:)

2021-03-11 05:35 UTC, Dihlofos commented on src/pages/GameProccessPage/sanfranoid/Lives.ts
> +      el.src = '../../../assets/images/heart.png'
давай адрес картинки вынесем в settings?

2021-03-11 05:35 UTC, Dihlofos commented on src/pages/GameProccessPage/sanfranoid/Sanfranoid.ts
> +  private _starting: boolean
Вот тут получается что состояние "starting" и "isCountinues" - это 2 разных состояния. Разница только в том, что у тебя в состоянии starting нет текста "Пауза" - Думаю текст нужно добавить, например "Нажмите пробел для начала игры" И тогда можно по сути ограничиться одним состоянием "_isContinues" И просто прокидывать туда нужный текст, если игра только стартовала, запускаем паузу со стартовыми словами, если игра уже вовсю идет и человек поставил паузу - делаем тоже самое, но с другим текстом.

2021-03-14 03:39 UTC, malig requested changes

2021-03-14 03:39 UTC, malig commented on src/pages/GameProccessPage/sanfranoid/Lives.ts
> +    this.img.forEach((img: any) => {
Стоит как-то оптимизировать, хотя бы не гонять forEach на каждую отрисовку (а их очень много), а вызывать только при изменение кол-ва жизни. Тут бы мемофункция как раз пригодилась

2021-03-14 03:39 UTC, malig commented on src/pages/GameProccessPage/sanfranoid/Sanfranoid.ts
> +    }
Мне кажется все это должно быть в паузе. Должно быть событие on/off у паузы, которые торчат наружу, а внутри биндинг кнопок, статусы и прочая логика. А снаружи клиент (Sanfranoid), только подписывается на on/off и останавливает или продолжает игру

2021-03-14 07:20 UTC, Domion-M commented on src/pages/GameProccessPage/sanfranoid/Lives.ts
> +    this.img.forEach((img: any) => {
по-другому не как . так как мы все стираем и заново нужно отрисовать

2021-03-14 07:37 UTC, Domion-M commented on src/pages/GameProccessPage/sanfranoid/Sanfranoid.ts
> +    }
тут я не понял как ты имел введу просто нам надо управлять внешним состоянием и нельзя передать его в дочерний

2021-03-14 07:44 UTC, malig commented on src/pages/GameProccessPage/sanfranoid/Sanfranoid.ts
> +    }
`new Pause({
	on: () ={ gameStop }
	off: () ={ gameContinue }
})`

2021-03-14 07:52 UTC, Domion-M commented on src/pages/GameProccessPage/sanfranoid/Sanfranoid.ts
> +  private _starting: boolean
Тут тоже надо подумать посидеть с этим может в техдолг записать

2021-03-14 08:05 UTC, malig commented on src/pages/GameProccessPage/sanfranoid/Sanfranoid.ts
> +    }
Хотя можно и не делать, это же вообще задач из бэклога)

2021-03-14 08:05 UTC, malig approved these changes

2021-03-20 14:28 UTC, merged