Sprint/3/2/ ssr
sanfranboys/arcanoid pull request #49
Opened 2021-03-10 06:42 UTC by malig

2021-03-10 18:53 UTC, Dihlofos requested changes
Большую работу проделал! я поглядел, все работает, класс!)
Отписал, по мелочи моменты поправить.

2021-03-10 18:53 UTC, Dihlofos commented on src/pages/AuthPage/components/Auth/Auth.tsx
> +// import { yupResolver } from '@hookform/resolvers/yup'
Я посмотрел, можно вернуть yup, для этого проставь разрешение .js
`import { yupResolver } from '@hookform/resolvers/yup.js`

И в eslint конфиге добавь правило 'import/extensions': 1,

Таким образом мы остаемся с полным функционалом, а варнинги помогут нам не забыть разобраться с этим вопросом, потому что думаю решение в итоге окажется элементарным)

2021-03-11 07:54 UTC, eshturman requested changes

2021-03-11 07:54 UTC, eshturman commented on src/client.tsx
> -import { startServiceWorker } from './utils'
не очень правильно) Отталкивайтесь от env переменной и в режиме разработки выключайте sw

2021-03-11 07:54 UTC, eshturman commented on src/pages/AuthPage/components/Auth/Auth.tsx
> +// import { yupResolver } from '@hookform/resolvers/yup'
Да, выпиливать функционал не нужно

2021-03-11 11:08 UTC, Dihlofos approved these changes

2021-03-11 11:13 UTC, merged