[WIP]sprint/3/3 middleware
sanfranboys/arcanoid pull request #53
Opened 2021-03-15 18:16 UTC by Domion-M

2021-03-16 02:20 UTC, malig approved these changes

2021-03-16 02:20 UTC, malig commented on src/middleware.ts
> +// хардкод куки
давайте не будем пушить закомменченный код

2021-03-16 02:20 UTC, malig commented on src/middleware.ts
> +console.log(res.status);
Выводы в консоль давайте не будем заливать

2021-03-16 05:30 UTC, Dihlofos commented on src/middleware.ts
> +console.log(res.status);
это PR для Жени, чтобы посмотреть код и помочь, он помечен флагом WIP то есть Work In Progress, он не подразумевает сливания

2021-03-17 07:51 UTC, Dihlofos approved these changes

2021-03-18 04:57 UTC, eshturman requested changes

2021-03-18 04:57 UTC, eshturman commented on src/middleware.ts
> +export const auth = async (req:any, _res:any, next:NextFunction) => {
Затипизируй request и response

2021-03-18 04:57 UTC, eshturman commented on src/server.ts
> +  // eslint-disable-next-line @typescript-eslint/no-shadow
Нужно избавиться от этого

2021-03-18 07:12 UTC, malig approved these changes

2021-03-20 13:10 UTC, merged